### ISSUE TITLE
Reachable workspace

### ISSUE THREAD

**Issue by pattacini** [skkkumar/MakeItRoll_HumanoidRobot#4]
The hand does barely touch the ball.
What are the steps to extend the reachable space?

**Comment by skkkumar** [comment]
By adding Torso and enabling Pitch and disabling yaw and roll the robot can bend forward and reachable space can be achieved. Am I right ?

**Comment by pattacini** [comment]
Yes, you are.
Enable the yaw; it'll help out as well.

**Comment by skkkumar** [comment]
I added the Torso with pitch and yaw enabled. Fixed
