### ISSUE TITLE
Interfaces should be open from one place (i.e. within configure())

### ISSUE THREAD

**Issue by pattacini** [skkkumar/MakeItRoll_HumanoidRobot#6]
You keep on opening and closing interfaces in the methods

**Comment by skkkumar** [comment]
At first I opened the interfaces from Configure () but the program will stop with the error "yarpdev: **_ERROR**_ driver <remote_controlboard> was found but could not open " and another error saying device already open at ... 

I will have to open head, left hand and right hand and use them simultaneously . So I will have to place them in separate Polydrive and open them. The first device is opening then when opening the second I get the above error.

**Comment by pattacini** [comment]
The driver must be open only once, usually in the `configure()` method, whereas the relative interfaces are simply views that can be defined whenever you deem necessary.

**Comment by skkkumar** [comment]
Fixed.
