### ISSUE TITLE
Sync vs. Non-sync

### ISSUE THREAD

**Issue by pattacini** [skkkumar/MakeItRoll_HumanoidRobot#7]
What's the problem with this [call](https://github.com/skkkumar/iCubProgAss/blob/master/make-it-roll%202/src/main.cpp#L204)?

**Comment by skkkumar** [comment]
goToPose moves to the specified Cartesian point but doesnt wait for the reply and so I had to use the waitMotionDone. 

goToPoseSync moves to the specified Cartesian point and replies once the motion is done. So using this I dont have to write the waitMotionDone. 

Am I right ?

**Comment by pattacini** [comment]
That's not correct.

`goToPose` serves for tracking purpose, hence it does not wait for any reply and a successive call to `waitMotionDone` might bring about unpredictable results.

Conversely, `goToPoseSync` does wait for the server's reply upon movement initiation and not when the motion is accomplished. With this method, you can safely call the `waitMotionDone` just afterwards.

**Comment by skkkumar** [comment]
yes corrected. Thank you. 

Fixed
