### ISSUE TITLE
Retrieving 3D point

### ISSUE THREAD

**Issue by pattacini** [skkkumar/MakeItRoll_HumanoidRobot#8]
What's the reason for discriminating between [left and right](https://github.com/skkkumar/iCubProgAss/blob/master/make-it-roll%202/src/main.cpp#L115) to retrieve 3D point?

**Comment by skkkumar** [comment]
In the Cartesian space the left and right has different 3D points. So to locate the position of the blue ball I will have to discriminate between left and right. 

But here I dont used the left. and I for got to remove that code as I will not be using it. 
Thank you.

**Comment by skkkumar** [comment]
Fixed.
